spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.universe.demo.springboot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml